# Generated by Django 6.0.6 on 2026-06-27 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('national_id', models.CharField(max_length=20, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='employees/passports/')),
                ('employment_type', models.CharField(choices=[('casual', 'Casual'), ('permanent', 'Permanent')], max_length=20)),
                ('job_role', models.CharField(max_length=100)),
                ('date_employed', models.DateField()),
                ('next_of_kin_name', models.CharField(max_length=200)),
                ('next_of_kin_phone', models.CharField(max_length=20)),
                ('sha_number', models.CharField(blank=True, max_length=50, null=True)),
                ('nssf_number', models.CharField(blank=True, max_length=50, null=True)),
                ('monthly_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('daily_wage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
    ]
