# Generated by Django 6.0.6 on 2026-06-27 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField(help_text='Date the expense was incurred.')),
                ('category', models.CharField(choices=[('office_supplies', 'Office Supplies'), ('safety_equipment', 'Safety Equipment'), ('transport', 'Transport'), ('courier', 'Courier Services'), ('communication', 'Communication'), ('utilities', 'Utilities'), ('maintenance', 'Maintenance'), ('cleaning', 'Cleaning'), ('government_fees', 'Government Fees'), ('miscellaneous', 'Miscellaneous')], max_length=50)),
                ('description', models.TextField(help_text='Describe what was purchased or the service received.')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer')], max_length=20)),
                ('receipt_number', models.CharField(blank=True, help_text='Optional receipt or transaction reference.', max_length=100, null=True)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='expense_receipts/')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
    ]
