# Generated by Django 6.0.6 on 2026-06-30 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('period_type', 'start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='CasualPayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_worked', models.PositiveIntegerField()),
                ('daily_wage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('mpesa_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(limit_choices_to={'employment_type': 'casual'}, on_delete=django.db.models.deletion.PROTECT, related_name='casual_payrolls', to='employees.employee')),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='casual_payrolls', to='payroll.payrollperiod')),
            ],
            options={
                'ordering': ('payment_status', 'employee__full_name'),
                'unique_together': {('employee', 'payroll_period')},
            },
        ),
        migrations.CreateModel(
            name='PermanentPayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('overtime', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bonuses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paye', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sha', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nssf', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('mpesa_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(limit_choices_to={'employment_type': 'permanent'}, on_delete=django.db.models.deletion.PROTECT, related_name='permanent_payrolls', to='employees.employee')),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permanent_payrolls', to='payroll.payrollperiod')),
            ],
            options={
                'ordering': ('payment_status', 'employee__full_name'),
                'unique_together': {('employee', 'payroll_period')},
            },
        ),
    ]
