# Generated by Django 6.0.6 on 2026-06-30 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_date', models.DateField()),
                ('supplier', models.CharField(blank=True, max_length=150, null=True)),
                ('litres', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('receipt_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('receipt_file', models.FileField(upload_to='fuel/receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fuel_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FuelIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_date', models.DateField()),
                ('litres', models.DecimalField(decimal_places=2, max_digits=10)),
                ('odometer_reading', models.DecimalField(decimal_places=1, help_text='Vehicle odometer or machine hour-meter reading at the time of fueling.', max_digits=12)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_issues', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['vehicle', 'fuel_date', 'created_at'],
            },
        ),
    ]
