# Generated by Django 6.0.6 on 2026-06-27 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_identifier', models.CharField(help_text='Vehicle plate number or machine name (e.g. KDJ 123A, Wheel Loader 1)', max_length=150, unique=True)),
                ('assigned_operator', models.CharField(blank=True, help_text='Driver or machine operator (stored as text)', max_length=150, null=True)),
                ('opening_odometer_reading', models.DecimalField(decimal_places=1, help_text='Initial odometer or hour-meter reading', max_digits=12)),
                ('closing_odometer_reading', models.DecimalField(blank=True, decimal_places=1, help_text='Final odometer or hour-meter reading', max_digits=12, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
