# Generated by Django 6.0.6 on 2026-06-27 02:41

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=200, unique=True)),
                ('service_type', models.CharField(help_text='Examples: Fuel Supplier, Hardware Supplier, Blasting, Transport', max_length=150)),
                ('contact_person', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('physical_address', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['vendor_name'],
            },
        ),
        migrations.CreateModel(
            name='VendorTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('invoice_number', models.CharField(blank=True, help_text='Leave blank if no invoice exists.', max_length=100, null=True)),
                ('description', models.TextField(help_text='Products supplied or services rendered.')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Optional for services.', max_digits=12, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional for services.', max_digits=12, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Automatically calculated for goods. Enter manually for services.', max_digits=14)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('balance_due', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('paid', 'Paid')], editable=False, max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
    ]
